#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# Copyright (C) 2012 Yaacov Zamir (2012) <kobi.zamir@gmail.com>
# Author: Yaacov Zamir (2012) <kobi.zamir@gmail.com>

''' this list is for the gettext makemessages script.

    hcaldjango use the django localization system. this is a list of 
    strings used by libhdate and not found in the hcaldjango code tree.
'''

hcal_strings = [
    _('Sun'),
    _('Mon'),
    _('Tue'),
    _('Wed'),
    _('Thu'),
    _('Fri'),
    _('Sat'),
    _('Sunday'),
    _('Monday'),
    _('Tuesday'),
    _('Wednesday'),
    _('Thursday'),
    _('Friday'),
    _('Saturday'),
    _('Jan'),
    _('Feb'),
    _('Mar'),
    _('Apr'),
    _('May'),
    _('Jun'),
    _('Jul'),
    _('Aug'),
    _('Sep'),
    _('Oct'),
    _('Nov'),
    _('Dec'),
    _('January'),
    _('February'),
    _('March'),
    _('April'),
    _('June'),
    _('July'),
    _('August'),
    _('September'),
    _('October'),
    _('November'),
    _('December'),
    _('Tishrei'),
    _('Cheshvan'),
    _('Kislev'),
    _('Tevet'),
    _('Sh\'vat'),
    _('Adar'),
    _('Nisan'),
    _('Iyyar'),
    _('Sivan'),
    _('Tamuz'),
    _('Av'),
    _('Elul'),
    _('Adar I'),
    _('Adar II'),
    _('Rosh Hashana I'),
    _('Rosh Hashana II'),
    _('Tzom Gedaliah'),
    _('Yom Kippur'),
    _('Sukkot'),
    _('Hol hamoed Sukkot'),
    _('Hoshana raba'),
    _('Simchat Torah'),
    _('Chanukah'),
    _('Asara B\'Tevet'),
    _('Tu B\'Shvat'),
    _('Ta\'anit Esther'),
    _('Purim'),
    _('Shushan Purim'),
    _('Pesach'),
    _('Hol hamoed Pesach'),
    _('Yom HaAtzma\'ut'),
    _('Lag B\'Omer'),
    _('Erev Shavuot'),
    _('Shavuot'),
    _('Tzom Tammuz'),
    _('Tish\'a B\'Av'),
    _('Tu B\'Av'),
    _('Yom HaShoah'),
    _('Yom HaZikaron'),
    _('Yom Yerushalayim'),
    _('Shmini Atzeret'),
    _('Pesach VII'),
    _('Pesach VIII'),
    _('Shavuot II'),
    _('Sukkot II'),
    _('Pesach II'),
    _('Family Day'),
    _('Memorial day for fallen whose place of burial is unknown'),
    _('Rabin memorial day'),
    _('Zhabotinsky day'),
    _('Erev Yom Kippur'),
    _('Yitzhak Rabin memorial day'),
    _('Zeev Zhabotinsky day'),
    _('in the Omer'),
    _('none'),
    _('Bereshit'),
    _('Noach'),
    _('Lech-Lecha'),
    _('Vayera'),
    _('Chayei Sara'),
    _('Toldot'),
    _('Vayetzei'),
    _('Vayishlach'),
    _('Vayeshev'),
    _('Miketz'),
    _('Vayigash'),
    _('Vayechi'),
    _('Shemot'),
    _('Vaera'),
    _('Bo'),
    _('Beshalach'),
    _('Yitro'),
    _('Mishpatim'),
    _('Terumah'),
    _('Tetzaveh'),
    _('Ki Tisa'),
    _('Vayakhel'),
    _('Pekudei'),
    _('Vayikra'),
    _('Tzav'),
    _('Shmini'),
    _('Tazria'),
    _('Metzora'),
    _('Achrei Mot'),
    _('Kedoshim'),
    _('Emor'),
    _('Behar'),
    _('Bechukotai'),
    _('Bamidbar'),
    _('Nasso'),
    _('Beha\'alotcha'),
    _('Sh\'lach'),
    _('Korach'),
    _('Chukat'),
    _('Balak'),
    _('Pinchas'),
    _('Matot'),
    _('Masei'),
    _('Devarim'),
    _('Vaetchanan'),
    _('Eikev'),
    _('Re\'eh'),
    _('Shoftim'),
    _('Ki Teitzei'),
    _('Ki Tavo'),
    _('Nitzavim'),
    _('Vayeilech'),
    _('Ha\'Azinu'),
    _('Vezot Habracha'),
    _('Vayakhel-Pekudei'),
    _('Tazria-Metzora'),
    _('Achrei Mot-Kedoshim'),
    _('Behar-Bechukotai'),
    _('Chukat-Balak'),
    _('Matot-Masei'),
    _('Nitzavim-Vayeilech'),
    _('translator'),
]

